---
on:
  push:
    branches:
      - master
jobs:
  publish_modules:
    runs-on: python:3.7.6
    env:
      GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      ARTIFACTORY_URL: https://arti.tw.ee/artifactory/terraform-kubernetes
    steps:
      - name: Upgrade git
        run: sudo apt-get install git

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

        #      - name: Publish modules
        #        run: ./tools/publish.sh -publish -compare-url="https://github.com/transferwise/terraform-kubernetes/compare/$(git rev-parse HEAD^)...$(git rev-parse HEAD)"
      - name: test
        run: echo $(git rev-parse HEAD) && echo $(git rev-parse HEAD^)

      - name: test2
        run: ./tools/publish.sh
