---
on:
  push:
    branches:
      - 'master'
jobs:
  publish_modules:
    runs-on: ubuntu-latest
    container: golang:1.16.2
    env:
      GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      ARTIFACTORY_URL: https://arti.tw.ee/artifactory/terraform-kubernetes
    steps:
      - name: Upgrade git
        run: apt-get update && apt-get install git -y

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

        #      - name: Publish modules
        #        run: ./tools/publish.sh -publish -compare-url="https://github.com/transferwise/terraform-kubernetes/compare/$(git rev-parse HEAD^)...$(git rev-parse HEAD)"
      - name: test
        run: echo $(git rev-parse HEAD) && echo $(git rev-parse HEAD^)

      - name: test2
        run: ./tools/publish.sh

      - name: vars
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: print var
        run: echo "$VERSION"

      - name: version wow
        run: |
          DATETIME=$(date -u '+%y%m%d.%H%M%S')
          COMMIT=$(git rev-parse --short HEAD)
          echo "VERSION=1.${DATETIME}-${COMMIT}" >> $GITHUB_ENV
